
trigger:
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'precise-ui:$(build.buildId)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
    npm run build:demo
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'Build Kitchensink'

- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  displayName: 'Deploy Kitchensink'
