// AUTO GENERATED by /tools/convert-icons.js
// COMING FROM material-design-icons
// (c) Material UI
// Licensed under MIT
// https://github.com/mui-org/material-ui
import * as React from 'react';
import * as enzyme from 'enzyme';
import * as icons from './icons';

describe('Generated icons', () => {
  it('should render AccountBalance icon', () => {
    const Component = icons.AccountBalance;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render AccountCircle icon', () => {
    const Component = icons.AccountCircle;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Announcement icon', () => {
    const Component = icons.Announcement;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Bookmark icon', () => {
    const Component = icons.Bookmark;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Book icon', () => {
    const Component = icons.Book;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Build icon', () => {
    const Component = icons.Build;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Cached icon', () => {
    const Component = icons.Cached;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render CheckCircle icon', () => {
    const Component = icons.CheckCircle;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Dashboard icon', () => {
    const Component = icons.Dashboard;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render DateRange icon', () => {
    const Component = icons.DateRange;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Delete icon', () => {
    const Component = icons.Delete;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Description icon', () => {
    const Component = icons.Description;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Done icon', () => {
    const Component = icons.Done;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Event icon', () => {
    const Component = icons.Event;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ExitToApp icon', () => {
    const Component = icons.ExitToApp;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Favorite icon', () => {
    const Component = icons.Favorite;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FavoriteBorder icon', () => {
    const Component = icons.FavoriteBorder;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Feedback icon', () => {
    const Component = icons.Feedback;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render HelpOutline icon', () => {
    const Component = icons.HelpOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Home icon', () => {
    const Component = icons.Home;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ImportantDevices icon', () => {
    const Component = icons.ImportantDevices;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Info icon', () => {
    const Component = icons.Info;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render InfoOutline icon', () => {
    const Component = icons.InfoOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Label icon', () => {
    const Component = icons.Label;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render LabelOutline icon', () => {
    const Component = icons.LabelOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Language icon', () => {
    const Component = icons.Language;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Pageview icon', () => {
    const Component = icons.Pageview;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render PowerSettingsNew icon', () => {
    const Component = icons.PowerSettingsNew;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Print icon', () => {
    const Component = icons.Print;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render QuestionAnswer icon', () => {
    const Component = icons.QuestionAnswer;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Restore icon', () => {
    const Component = icons.Restore;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Search icon', () => {
    const Component = icons.Search;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Settings icon', () => {
    const Component = icons.Settings;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render SwapVert icon', () => {
    const Component = icons.SwapVert;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ThumbDown icon', () => {
    const Component = icons.ThumbDown;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ThumbUp icon', () => {
    const Component = icons.ThumbUp;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Update icon', () => {
    const Component = icons.Update;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render VerifiedUser icon', () => {
    const Component = icons.VerifiedUser;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ViewCarousel icon', () => {
    const Component = icons.ViewCarousel;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ViewColumn icon', () => {
    const Component = icons.ViewColumn;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Visibility icon', () => {
    const Component = icons.Visibility;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render VisibilityOff icon', () => {
    const Component = icons.VisibilityOff;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Error icon', () => {
    const Component = icons.Error;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Warning icon', () => {
    const Component = icons.Warning;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render PlayArrow icon', () => {
    const Component = icons.PlayArrow;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Replay icon', () => {
    const Component = icons.Replay;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render VideoLibrary icon', () => {
    const Component = icons.VideoLibrary;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Email icon', () => {
    const Component = icons.Email;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render MailOutline icon', () => {
    const Component = icons.MailOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Phone icon', () => {
    const Component = icons.Phone;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Add icon', () => {
    const Component = icons.Add;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render AddCircle icon', () => {
    const Component = icons.AddCircle;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render AddCircleOutline icon', () => {
    const Component = icons.AddCircleOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ContentCopy icon', () => {
    const Component = icons.ContentCopy;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Create icon', () => {
    const Component = icons.Create;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FilterList icon', () => {
    const Component = icons.FilterList;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Remove icon', () => {
    const Component = icons.Remove;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render RemoveCircle icon', () => {
    const Component = icons.RemoveCircle;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render RemoveCircleOutline icon', () => {
    const Component = icons.RemoveCircleOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Send icon', () => {
    const Component = icons.Send;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Sort icon', () => {
    const Component = icons.Sort;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Unarchive icon', () => {
    const Component = icons.Unarchive;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render LocationSearching icon', () => {
    const Component = icons.LocationSearching;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Widgets icon', () => {
    const Component = icons.Widgets;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render BorderClear icon', () => {
    const Component = icons.BorderClear;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render CreateNewFolder icon', () => {
    const Component = icons.CreateNewFolder;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FileDownload icon', () => {
    const Component = icons.FileDownload;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FileUpload icon', () => {
    const Component = icons.FileUpload;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Folder icon', () => {
    const Component = icons.Folder;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FolderOpen icon', () => {
    const Component = icons.FolderOpen;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FolderShared icon', () => {
    const Component = icons.FolderShared;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render KeyboardArrowDown icon', () => {
    const Component = icons.KeyboardArrowDown;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render KeyboardArrowLeft icon', () => {
    const Component = icons.KeyboardArrowLeft;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render KeyboardArrowRight icon', () => {
    const Component = icons.KeyboardArrowRight;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render KeyboardArrowUp icon', () => {
    const Component = icons.KeyboardArrowUp;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Adjust icon', () => {
    const Component = icons.Adjust;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Edit icon', () => {
    const Component = icons.Edit;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Filter1 icon', () => {
    const Component = icons.Filter1;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FilterNone icon', () => {
    const Component = icons.FilterNone;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render LocalOffer icon', () => {
    const Component = icons.LocalOffer;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render MyLocation icon', () => {
    const Component = icons.MyLocation;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Place icon', () => {
    const Component = icons.Place;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Apps icon', () => {
    const Component = icons.Apps;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ArrowDropDown icon', () => {
    const Component = icons.ArrowDropDown;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ArrowDropUp icon', () => {
    const Component = icons.ArrowDropUp;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ArrowForward icon', () => {
    const Component = icons.ArrowForward;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Cancel icon', () => {
    const Component = icons.Cancel;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Check icon', () => {
    const Component = icons.Check;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Close icon', () => {
    const Component = icons.Close;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Fullscreen icon', () => {
    const Component = icons.Fullscreen;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FullscreenExit icon', () => {
    const Component = icons.FullscreenExit;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Menu icon', () => {
    const Component = icons.Menu;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render MoreHoriz icon', () => {
    const Component = icons.MoreHoriz;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render MoreVert icon', () => {
    const Component = icons.MoreVert;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render UnfoldLess icon', () => {
    const Component = icons.UnfoldLess;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render UnfoldMore icon', () => {
    const Component = icons.UnfoldMore;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render ConfirmationNumber icon', () => {
    const Component = icons.ConfirmationNumber;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Sync icon', () => {
    const Component = icons.Sync;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render SyncDisabled icon', () => {
    const Component = icons.SyncDisabled;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render SyncProblem icon', () => {
    const Component = icons.SyncProblem;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Notifications icon', () => {
    const Component = icons.Notifications;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Person icon', () => {
    const Component = icons.Person;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Public icon', () => {
    const Component = icons.Public;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Share icon', () => {
    const Component = icons.Share;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render CheckBox icon', () => {
    const Component = icons.CheckBox;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render CheckBoxOutlineBlank icon', () => {
    const Component = icons.CheckBoxOutlineBlank;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render IndeterminateCheckBox icon', () => {
    const Component = icons.IndeterminateCheckBox;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render RadioButtonChecked icon', () => {
    const Component = icons.RadioButtonChecked;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render RadioButtonUnchecked icon', () => {
    const Component = icons.RadioButtonUnchecked;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Star icon', () => {
    const Component = icons.Star;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FitToWidth icon', () => {
    const Component = icons.FitToWidth;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render FitToHeight icon', () => {
    const Component = icons.FitToHeight;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Page icon', () => {
    const Component = icons.Page;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render PDFFile icon', () => {
    const Component = icons.PDFFile;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render PDFFileOutline icon', () => {
    const Component = icons.PDFFileOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render Video icon', () => {
    const Component = icons.Video;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });

  it('should render VideoOutline icon', () => {
    const Component = icons.VideoOutline;
    const wrapper = enzyme.mount(<Component width="12" height="12" />);
    expect(wrapper).toMatchSnapshot();
  });
});
