name: Build CI

on:
  release:
    types:
      - created

jobs:
  deploy_www:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: |
        npm install
    - name: Build Release with Styleguidist
      run: |
        npm run build:demo
        cd styleguide
        ln -s index.html 404.html
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}